<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
      <class name="predictive.MyTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:predictive.MyTest@d9b7c1]" name="setUp" is-config="true" duration-ms="8" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="test1()[pri:0, instance:predictive.MyTest@d9b7c1]" name="test1" duration-ms="6" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:predictive.MyTest@d9b7c1]" name="setUp" is-config="true" duration-ms="0" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:predictive.MyTest@d9b7c1]" name="test2" duration-ms="2" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<[hello]> but was:<[]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<[hello]> but was:<[]>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
	at predictive.MyTest.test2(MyTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:predictive.MyTest@d9b7c1]" name="setUp" is-config="true" duration-ms="1" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="test3()[pri:0, instance:predictive.MyTest@d9b7c1]" name="test3" duration-ms="0" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:predictive.MyTest@d9b7c1]" name="setUp" is-config="true" duration-ms="0" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="test4()[pri:0, instance:predictive.MyTest@d9b7c1]" name="test4" duration-ms="0" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:predictive.MyTest@d9b7c1]" name="setUp" is-config="true" duration-ms="0" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="test5()[pri:0, instance:predictive.MyTest@d9b7c1]" name="test5" duration-ms="0" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:predictive.MyTest@d9b7c1]" name="setUp" is-config="true" duration-ms="0" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="test6()[pri:0, instance:predictive.MyTest@d9b7c1]" name="test6" duration-ms="1" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6 -->
        <test-method status="FAIL" signature="test7()[pri:0, instance:predictive.MyTest@d9b7c1]" name="test7" duration-ms="1" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<hello> but was:<[hello]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<hello> but was:<[hello]>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
	at predictive.MyTest.test7(MyTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test7 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:predictive.MyTest@d9b7c1]" name="setUp" is-config="true" duration-ms="0" started-at="2014-03-26T23:42:21Z" finished-at="2014-03-26T23:42:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- predictive.MyTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
